### ISSUE TITLE
Fix web_console_controls.py

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#685]
A general overhaul of this test case is required, This feature's UI has changed, the images for the following, no longer exist.  The functionality for these buttons was moved into a menu.  

dock_button = 'dock_to_side.png'
dock_button_activated = 'dock_to_side_activated.png'
separate_window_button = 'separate_window.png'

Please rework the test case to use the controls from inside the menu. Also, please discontinue use of hard coded regions.

**Comment by IonutBudeanu** [comment]
FIxed in https://github.com/mozilla/iris/tree/issue_685.

Please review.

Thank You

**Comment by tracywalker** [comment]
Ionut, this works great on Linux. However it fails on both OSX and Windows.  On OSX it fails to fine the close button tooltip.  It appears to be hovering the tab close button instead of the expected console close button. If I interact with the mouse to make it hover the correct "x", Iris still doesn't find the tooltip.  On Windows it fails right away, by not finding the dock_to_side control.  Please investigate and address these failure. 
Thanks

**Comment by IonutBudeanu** [comment]
Fixed in https://github.com/mozilla/iris/commit/e52f32662dc1683792a808774333983ef588f4e6

Please review.

Thank You

**Comment by silviuFlorin** [comment]
Reviewed web_console_controls test. Updated the way regions are created. Ran test on all platforms and it passed. Code approved

**Comment by tracywalker** [comment]
Also looked at this on macMini where it was failing for me before.  Not any more.  It looks good now.

**Comment by tracywalker** [comment]
Also looked at this on macMini where it was failing for me before.  Not any more.  It looks good now.  However, the PR to dev will not merge automatically.   Can you manually rebase the issue_685 branch please.  Thank you.
